version: "3.5"

services:
  api01: &api
    image: alanlopes/rinha-2024q1-dotnet
    restart: always
    hostname: api01
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DB_HOSTNAME: db
      Kestrel__Endpoints__Http__Url: http://0.0.0.0:3001
    deploy:
      resources:
        limits:
          cpus: "0.9"
          memory: "340MB"
#  api02:
#    <<: *api
#    hostname: api02
#    depends_on: 
#      - db
#    ports:
#      - '3002:3002'
#    environment:
#      ASPNETCORE_ENVIRONMENT: Development
#      DB_HOSTNAME: db
#      Kestrel__Endpoints__Http__Url: http://0.0.0.0:3002
   
  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/Config/init.sql
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "200MB"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "10MB"
      
networks: 
  default:
    driver: bridge
    name: rinha-nginx-2024q1